---
title: "Municipal Elections"
author: ""
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---


```{r results='hide', echo=FALSE, include=FALSE}
p_needed <- c("tidyverse",
              "here",
              "readxl",
              "data.table",
              "magrittr",
              "rvest",
              "htmltab",
              "xml2",
              "gt",
              "gtExtras"
)
packages <- rownames(installed.packages())
p_to_install <- p_needed[!(p_needed %in% packages)]
if (length(p_to_install) > 0) {
  install.packages(p_to_install)
}
lapply(p_needed, require, character.only = TRUE)
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
Elections <- read_csv(here("static", "htmlplots", "Data", "Elections.csv"), col_names = TRUE)
```



```{r echo=FALSE}
my_pal <- scales::col_numeric(
  paletteer::paletteer_d(
    palette = "ggsci::red_material"
    ) %>% as.character(),
  domain = NULL
  )

```

<br><br>

### Basic differences between "Normal" and "Kaso" 

```{r echo=FALSE, results='asis', message=FALSE, warning=FALSE}
Elections %>%
  group_by(Year, Kaso2) %>%
  filter(LDP>=0 & LDP <=1) %>%
  filter(JCP>=0 & JCP <=1) %>%
  mutate(EldPop = EldPop/100) %>%
    dplyr::summarize(`LDP-SMD` = mean(LDP, na.rm=TRUE),
                     `LDP-PR` = mean(LDPPR, na.rm=TRUE),
                     `JCP-SMD` = mean(JCP, na.rm=TRUE),
                     `JCP-PR` = mean(JCPPR, na.rm=TRUE),
                     Turnout = mean(Turnout, na.rm=TRUE),
                     FStrength = mean(Fstrength, na.rm=TRUE),
                     Elderly = mean(EldPop, na.rm=TRUE)) %>%
  gt(rowname_col = "Kaso2") %>%
  fmt_number(
    columns = 2:9,
    decimals = 2 # decrease decimal places
    ) %>%
  tab_style(
    style = list(
      cell_borders(
        sides = "left",
        color = "black",
        weight = px(3)
      )
    ),
    locations = list(
      cells_body(
        columns = vars(`JCP-SMD`, Turnout)
      ))) %>%
  tab_options(
    column_labels.border.top.color = "black",
    column_labels.border.bottom.color = "black",
    table_body.border.bottom.color = "black",
    table_body.hlines.color = "white"
    ) %>%
  tab_header(
    title = md("**Municipal characteristics**"),
    subtitle = md("*Aggregated by fiscal profiles*")
  ) %>%
    data_color(
    columns = 2:9,
    colors = my_pal
    )
```

<br><br>

### Detailed differences (including types of "Kaso")

```{r echo=FALSE, results='asis', message=FALSE, warning=FALSE}
Elections %>%
  group_by(Year, Kaso) %>%
  filter(LDP>=0 & LDP <=1) %>%
  filter(JCP>=0 & JCP <=1) %>%
  mutate(EldPop = EldPop/100) %>%
    dplyr::summarize(`LDP-SMD` = mean(LDP, na.rm=TRUE),
                     `LDP-PR` = mean(LDPPR, na.rm=TRUE),
                     `JCP-SMD` = mean(JCP, na.rm=TRUE),
                     `JCP-PR` = mean(JCPPR, na.rm=TRUE),
                     Turnout = mean(Turnout, na.rm=TRUE),
                     FStrength = mean(Fstrength, na.rm=TRUE),
                     Elderly = mean(EldPop, na.rm=TRUE)) %>%
  gt(rowname_col = "Kaso") %>%
  fmt_number(
    columns = 2:9,
    decimals = 2 # decrease decimal places
    ) %>%
  tab_style(
    style = list(
      cell_borders(
        sides = "left",
        color = "black",
        weight = px(3)
      )
    ),
    locations = list(
      cells_body(
        columns = vars(`JCP-SMD`, Turnout)
      ))) %>%
  tab_options(
    column_labels.border.top.color = "black",
    column_labels.border.bottom.color = "black",
    table_body.border.bottom.color = "black",
    table_body.hlines.color = "white"
    ) %>%
  tab_header(
    title = md("**Municipal characteristics**"),
    subtitle = md("*Aggregated by fiscal profiles*")
  ) %>%
    data_color(
    columns = 2:9,
    colors = my_pal
    )
```

<br><br>