[build]
  command = "hugo"
#  functions = "functions"
  publish = "public"
  
[context.production.environment]
  HUGO_VERSION = "0.122.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "false"
  PYTHON_VERSION = "3.8"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.122.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.122.0"
  

[[redirects]]
  from = "https://kovsiannikov.netlify.app"
  to = "https://kovsiannikov.com"
  status = 301
  force = true
  
[[redirects]]
  from = "http://kovsiannikov.netlify.app"
  to = "https://kovsiannikov.com"
  status = 301
  force = true

[[redirects]]
  from = "https://kovsiannikov2.netlify.app"
  to = "https://kovsiannikov.com"
  status = 301
  force = true
  
[[redirects]]
  from = "http://kovsiannikov2.netlify.app"
  to = "https://kovsiannikov.com"
  status = 301
  force = true
  
[[redirects]]
  from = "http://kovsiannikov.com"
  to = "https://kovsiannikov.com"
  status = 301
  force = true
  
[[redirects]]
  from = "https://kovsiannikov.com/slides/eajs-2021/eajs-2021"
  to = "https://kovsiannikov.com/slides/sase-2021/sase-2021"
  status = 301
  force = true
  